### PR TITLE
Chore : Adding missing components of  compile_rust.yaml

### PR DESCRIPTION
**Pull request by puneeth072003**
### What kind of changes does this PR include?

-   [ ] Fixes or refactors
-   [ ] A new challenge
-   [ ] Additional documentation
-   [x] Something else

## Description
Completing the workflows
- [x] Cplus
- [x] go
- [x] rust

### CODE REVIEW

**Comment by puneeth072003** [comment]
# Sorry all links should have been #35
My bad

**Comment by puneeth072003** [comment]
### RUST workflow Completed
- [x] Rust

**Comment by commjoen** [comment]
can we make sure that, instead off the full target folder, we offer the executable only for download?

**Comment by puneeth072003** [comment]
> folder

Hmm...I'll try that and let you know

**Comment by puneeth072003** [comment]
@commjoen Let me know the changes are ok or not 
if they are then  i'll implement the same for other jobs and workflows.

**Comment by puneeth072003** [comment]
@commjoen i fixed it
please look at executable-C-linux-x64 and confirm
Screenshot 2023-09-20 094856

**Comment by puneeth072003** [comment]
is it ok?

**Review by commjoen — APPROVED** [review]
Thank you @puneeth072003 ! this fixes a lot of stuff!

**Pull request merged**
