### PR TITLE
update C/C++ compile CI to use the makefile instead

### PR DESCRIPTION
**Pull request by diamant3**
### What kind of changes does this PR include?

-   [ ] Fixes or refactors
-   [ ] A new challenge
-   [ ] Additional documentation
-   [x] Something else

#### Description

Continuation from #40(fix for integration phase)

I added the c++ compile CI to this fix

### Relations

N/A

### References

N/A

### Checklist:

-   [x] All the contributions made are solely the work of me and my co-authors
-   [ ] I tested the changes in this PR (if applicable)
-   [ ] I added unit tests to ensure my change works (when change in Java or on front-end code)
-   [ ] Quickbuild.sh is extended to compile the binary for all target environnments
-   [ ] Github actions are implemented to publish the new challenge
-   [ ] A spoil command is implemented to return the actual answer
-   [ ] The correct and incorrect answer strings are compliant with Contributing.md.
-   [x] The PR passes pre-commit hooks and automated tests

### CODE REVIEW

**Comment by commjoen** [comment]
It looks like https://github.com/OWASP/wrongsecrets-binaries/actions/runs/6377854242/job/17307293682?pr=42 is failing. can you please have a look?

**Comment by diamant3** [comment]
Hello, I'll try this later, let me draft for now

**Comment by commjoen** [comment]
Some things were not working with the previous PR, pelase have a look at https://github.com/OWASP/wrongsecrets-binaries/pull/43 (will merge it myself) and try to fix the issues here based on the results there sir @diamant3  :).

**Comment by diamant3** [comment]
Hello, I saw the #43, Thank you for the help! I'll open it again

**Comment by diamant3** [comment]
It's successful now, thank you so much!, the path to the binary is the problem, sorry I'm bad in paths 😅

**Review by commjoen — APPROVED** [review]
thank you! now the integration is complete again :) .

**Pull request merged**
